#!/bin/sh /etc/rc.common

START=90
STOP=99
USE_PROCD=1

start_service()
{
    config_load tuya_esp_daemon

    config_get enabled main enabled

    [ "$enabled" = "1" ] || return 0

    config_get device_id main device_id
    config_get device_secret main device_secret
    config_get product_id main product_id

    [ -n "$device_id" ] || {
        logger -t tuya-esp-daemon "Missing device_id"
        return 1
    }

    [ -n "$device_secret" ] || {
        logger -t tuya-esp-daemon "Missing device_secret"
        return 1
    }

    [ -n "$product_id" ] || {
        logger -t tuya-esp-daemon "Missing product_id"
        return 1
    }

    procd_open_instance

    procd_set_param command \
        /usr/bin/tuya-esp-daemon \
        -d "$device_id" \
        -s "$device_secret" \
        -p "$product_id"

    procd_set_param respawn

    procd_close_instance
}

service_triggers()
{
    procd_add_reload_trigger "tuya_esp_daemon"
}

reload_service()
{
    stop
    start
}